// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxCzyAv1HWOVrga-bZMdx4PiYOBPRYn4E',
    appId: '1:282587344772:web:b7421969e3f90c7810f7d1',
    messagingSenderId: '282587344772',
    projectId: 'jesusyouth-b30e1',
    authDomain: 'jesusyouth-b30e1.firebaseapp.com',
    storageBucket: 'jesusyouth-b30e1.firebasestorage.app',
    measurementId: 'G-LGRZKQ0LL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyGjwYovgSwCS7WxbywkAPLf0cjNezCxQ',
    appId: '1:282587344772:android:9eb2d4cabfeb4fd310f7d1',
    messagingSenderId: '282587344772',
    projectId: 'jesusyouth-b30e1',
    storageBucket: 'jesusyouth-b30e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0mVFZRfN2DVNGxRdEj2fw5RtjxFSMsYg',
    appId: '1:282587344772:ios:b381dca4c99b237010f7d1',
    messagingSenderId: '282587344772',
    projectId: 'jesusyouth-b30e1',
    storageBucket: 'jesusyouth-b30e1.firebasestorage.app',
    iosClientId: '282587344772-la8rg5pvh4tsleuahothq06g8f6qu23u.apps.googleusercontent.com',
    iosBundleId: 'com.tcr.jesusyouth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0mVFZRfN2DVNGxRdEj2fw5RtjxFSMsYg',
    appId: '1:282587344772:ios:b381dca4c99b237010f7d1',
    messagingSenderId: '282587344772',
    projectId: 'jesusyouth-b30e1',
    storageBucket: 'jesusyouth-b30e1.firebasestorage.app',
    iosClientId: '282587344772-la8rg5pvh4tsleuahothq06g8f6qu23u.apps.googleusercontent.com',
    iosBundleId: 'com.tcr.jesusyouth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxCzyAv1HWOVrga-bZMdx4PiYOBPRYn4E',
    appId: '1:282587344772:web:c72f4cb79b346a2b10f7d1',
    messagingSenderId: '282587344772',
    projectId: 'jesusyouth-b30e1',
    authDomain: 'jesusyouth-b30e1.firebaseapp.com',
    storageBucket: 'jesusyouth-b30e1.firebasestorage.app',
    measurementId: 'G-PPNT77M5FV',
  );
}
